language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - make install_packages
install:
  - sudo add-apt-repository -y ppa:kronoss/libgit2
  - sudo add-apt-repository -y ppa:mercurial-ppa/releases
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes libgit2-0 libgit2-dev
  - sudo apt-get install -y --force-yes mercurial
script:
  - make coverage
after_success:
  - coveralls