language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo add-apt-repository -y ppa:mercurial-ppa/releases
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes mercurial git
install:
  - pip install -r requirements.txt -r requirements-dev.txt
script:
  - make coverage
after_success:
  - coveralls
